### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by italy2010** [countercept/doublepulsar-detection-script#10]
C:\Users\dodo>C:\Users\dodo\Downloads\Compressed\doublepulsar-detection-script-master_2\doublepulsar-detection-script-master\detect_doublepulsar_smb.py   --ip xxxxxxxxxx
Traceback (most recent call last):
  File "C:\Users\dodo\Downloads\Compressed\doublepulsar-detection-script-master_2\doublepulsar-detection-script-master\detect_doublepulsar_smb.py", line 155, in <module>
    check_ip(ip)
  File "C:\Users\dodo\Downloads\Compressed\doublepulsar-detection-script-master_2\doublepulsar-detection-script-master\detect_doublepulsar_smb.py", line 98, in check_ip
    modified_trans2_session_setup[28] = tree_id[0]
IndexError: string index out of range

**Comment by EpicLPer** [comment]
Yep, same here.

**Comment by MichalPlays** [comment]
Yup, same error https://abload.de/img/erwdwk1g.jpg

**Comment by SaiGonSeamus** [comment]
I have the same error running under Debian 8.6

**Comment by countercept** [comment]
I haven't seen that specific error before and it's very difficult to know exactly what is happening without at least a PCAP of the network traffic to look at. 

However, the OS versions I have seen fail to get all the way through the protocol sequence have been ones that the implant itself cannot communicate with successfully either so the likelihood is that they won't be infected if so. For example, windows 10 and 2012 both fail but then I had the same with issue with the implant itself on those OS versions.

**Comment by marcellogiannoni** [comment]
I got the same problem here CentOs 7
It hangs if the command is run agains a list of IPs defined in a file

**python detect_doublepulsar_smp.py --file smb.lst**

if I run the command with a single IP 
 **python detect_doublepulsar_smp.py --ip 192.168.9.10**

I get:
_Traceback (most recent call last):
  File "./detect_doublepulsar_smb.py", line 169, in <module>
    check_ip(ip)
  File "./detect_doublepulsar_smb.py", line 94, in check_ip
    modified_tree_connect_request[32] = user_id[0]
IndexError: string index out of range_

This is happening at line 81
_session_setup_response = s.recv(1024)_ --> return nothing so it fails at the next statement 
_modified_tree_connect_request[32] = user_id[0]_

Not sure why this is happening  at the network traffic level. I just added a simple control to avoid the hanging if run the command against a list of IPs defined in a file

_session_setup_response = s.recv(1024) 
if session_setup_response == "":
    print "No Response from the socket"
    sys.exit()_

**Comment by NJC2** [comment]
I've tried using the built in Bash shell in Windows 10 Anniversary Edition and on my notebook running Linux-Mint.  I get the same error on both.

**Comment by g33xter** [comment]
![screen shot 2017-05-12 at 23 59 01](https://cloud.githubusercontent.com/assets/8503135/26023387/26472722-376f-11e7-958e-d57e60405d05.png)
Its working great without VPN, but when I enable VPN it start throwing errors.
