### ISSUE TITLE
not reading ips

### ISSUE THREAD

**Issue by calilinus** [countercept/doublepulsar-detection-script#3]
root@kali:~/doublepulsar-detection-script# python detect_doublepulsar_smb.py --ip 0.0.0.0
Traceback (most recent call last):
  File "detect_doublepulsar_smb.py", line 124, in <module>
    check_ip(ip)
  File "detect_doublepulsar_smb.py", line 50, in check_ip
    s.connect((host, port))
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

hi can i please get will with this erros? thank you

**Comment by vmizoules** [comment]
Hello !
Try to change 0.0.0.0 to a real IP address.
Regards
